name: Unity Project Notifier

on: [push]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Format Commit Message
        id: vars
        run: |
          MSG="${{ github.event.head_commit.message }}"
          TITLE=$(echo "$MSG" | head -n 1)
          BODY=$(echo "$MSG" | tail -n +2 | xargs)
          echo "commit_title=$TITLE" >> $GITHUB_OUTPUT
          echo "commit_body=$BODY" >> $GITHUB_OUTPUT

      - name: Send Message to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          # The Programmer role is now linked via its ID
          content: "Attention <@&1468586352797810821>"
          nodetail: true
          title: "Update for ${{ github.event.repository.name }}"
          description: |
            **Message:**
            ${{ steps.vars.outputs.commit_title }}

            **Description:**
            ${{ steps.vars.outputs.commit_body }}

            **Author:** ${{ github.actor }}

            **Repo:** [${{ github.repository }}](https://github.com/${{ github.repository }})  |  **Branch:** `${{ github.ref_name }}`
          color: 0x7289da
          url: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
